### ISSUE TITLE
[BUG] Sending this image crashes the bot

### ISSUE THREAD

**Issue by thebashforkbomber** [KarstSkarn/ChAIScrapper#2]
```
https://cdn.discordapp.com/attachments/1267607123517505546/1267787439196344371/no_image.jpg?ex=66aa0e8f&is=66a8bd0f&hm=b68553040ed8a5504034df60a1817aa559e951ba3d1ffa89973396172b3abcf9&
```
just crashes the bot. Resetting it just takes down the whole server. You have to do it via upload; not link

**Comment by KarstSkarn** [comment]
This may be a remnant that in our private version bot has some code related to image recognition and description using third party services. Probably I just let accidentally the posibility to detect when an user uploaded an image but the rest of code is missing.

Anyway a 1x1 pixel picture is prone to cause any sort of overflow or glitch due to its odd size tho. I'll check it out for the next patch
